version: '3.9'

services:
  api:
    build: .
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env.docker
    depends_on:
      - postgres
    volumes:
      - .:/app
    command: npm run start:dev

  postgres:
    image: postgres:15
    restart: always
    env_file: .env.docker
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - ${ADMINER_PORT}:${ADMINER_PORT}

volumes:
  pgdata:
